USE keepaccount;

DELETE FROM ACCOUNT;
DELETE FROM ACCOUNT_BALANCE;
DELETE FROM ANNUALLY_STAT_RECORD;
DELETE FROM BUDGET_PLAN WHERE CAT1_ID != 1;
DELETE FROM CURRENCY;
DELETE FROM DAILY_STAT_RECORD;
DELETE FROM INCOME_CAT1;
DELETE FROM INCOME_RECORD;
DELETE FROM MONTHLY_STAT_RECORD;
DELETE FROM PAYMENT_CAT1 WHERE CAT1_ID != 1;
DELETE FROM PAYMENT_CAT2;
DELETE FROM PAYMENT_RECORD;
DELETE FROM TRANSFER_CAT1;
DELETE FROM TRANSFER_RECORD;
